feat: Move check to be command rather than option as it can be called alone

diff --git a/sb b/sb
--- a/sb
+++ b/sb
@@ -25,18 +25,20 @@ readonly virtual_env_type_node='node'
 readonly project_type_django='django'
 readonly project_type_node='node'
 
+readonly command_build='build'
 readonly command_freeze='freeze'
 readonly command_restore='restore'
-readonly command_build='build'
 readonly command_run='run'
+readonly command_check='check'
 readonly command_print_config='print-config'
 readonly command_reset='reset'
 readonly command_scipt_run='script-run'
 readonly commands=(
+	"$command_build"
 	"$command_freeze"
 	"$command_restore"
-	"$command_build"
 	"$command_run"
+	"$command_check"
 	"$command_scipt_run"
 	"$command_print_config"
 	"$command_reset"
@@ -45,7 +47,6 @@ readonly commands=(
 readonly option_help='--help'
 readonly option_help_short='-h'
 readonly option_version='--version'
-readonly option_check='--check'
 readonly option_verbose='--verbose'
 readonly option_verbose_short='-v'
 readonly allowed_options_base=(
@@ -54,7 +55,6 @@ readonly allowed_options_base=(
 	"$option_verbose"
 	"$option_verbose_short"
 	"$option_version"
-	"$option_check"
 )
 
 readonly option_branch='--branch'
@@ -67,10 +67,14 @@ readonly run_command_allowed_options=( "$option_branch" "$option_branch_short" )
 
 readonly freeze_command_default_branch='master'
 
-readonly message_usage="usage: $script_name [$option_help|$option_help_short] [$option_version] [$option_verbose|$option_verbose_short] [$option_check] <command> [<args>]"
+readonly message_usage="usage: $script_name [$option_help|$option_help_short] [$option_version] [$option_verbose|$option_verbose_short] <command> [<args>]"
 readonly message_usage_help="$message_usage
 
 There are a number of possible commands:
+
+	${fm_yellow}$command_build		${fm_cyan}$script_name $command_build [--<project_short_name>|-<proj_cli_char> <project-branch>...]${fm_reset}
+			Builds each specified project and its dependant services with the specified
+			branches. Possible projects depend on your config file
 
 	${fm_yellow}$command_freeze		${fm_cyan}$script_name $command_freeze <project> [$option_branch|$option_branch_short <branch>]${fm_reset}
 			Freeze database for project. Uses the master branch by default
@@ -79,18 +83,19 @@ There are a number of possible commands:
 			Restores project database to last time the freeze command was run. Optionally
 			removes clean database after successful restore
 
-	${fm_yellow}$command_build		${fm_cyan}$script_name $command_build [--<project_short_name>|-<proj_cli_char> <project-branch>...]${fm_reset}
-			Builds each specified project and its dependant services with the specified
-			branches. Possible projects depend on your config file
-
 	${fm_yellow}$command_run		${fm_cyan}$script_name $command_run <project> [$option_branch|$option_branch_short <branch>] <command> [<args>]${fm_reset}
 			Loads project environment and runs required command in it
+
+	${fm_yellow}$command_check		${fm_cyan}$script_name $command_check${fm_reset}
+			Checks to ensure all required environment variables are set up and script is
+			accessible on your path
 
 	${fm_yellow}$command_reset		${fm_cyan}$script_name $command_reset${fm_reset}
 			Removes tmux sessions and unlocks waiting windows
 
 	${fm_yellow}$command_print_config	${fm_cyan}$script_name $command_print_config${fm_reset}
-			Prints out the config file found at $config_filepath. All commands depend on this project
+			Prints out the config file found at $config_filepath. All commands
+			depend on this file being accessible
 "
 readonly message_config_file_not_readable="The config file '$config_filepath' does not exist or is not readable"
 readonly message_check='Running environment check...'
@@ -1016,173 +1021,7 @@ function handle_base_options() {
 		"$option_version")
 			printf "$version\n"
 			;;
-		"$option_check")
-			load_config
-			check_env 'true' || return 1
-			;;
 	esac
-
-	return 0
-}
-
-# TODO: Check that om is in the PATH
-function check_env() {
-	local set_verbose="$1"
-	local verbose='false'
-	local vars_missing='false'
-
-	if [[ "$verbose_mode" = 'true' || "$set_verbose" = 'true' ]]; then
-		local verbose='true'
-		print_format "$style_command_title" "$message_check"
-	fi
-
-	for ev in "${env_vars_required[@]}"; do
-		if [[ -z "${!ev+x}" ]]; then
-			local vars_missing='true'
-			printf "Checking '$ev'... ${fm_red}UNSET${fm_reset}\n"
-		else
-			if [[ "$verbose" = 'true' ]]; then
-				printf "Checking '$ev'... ${fm_green}OK${fm_reset}\n"
-			fi
-		fi
-	done
-
-	if [[ "$vars_missing" = 'true' ]]; then
-		printf "\n${fm_red}CHECK FAILED${fm_reset}\n"
-		printf "Please set the ${fm_red}UNSET${fm_reset} environment variables above before running the program\n"
-		return 1
-	elif [[ "$verbose" = 'true' ]]; then
-		printf "\n${fm_green}CHECK PASSED${fm_reset}\n"
-	fi
-
-	return 0
-}
-
-function freeze() {
-	local project="$1"
-	local -i project_i=$(get_project_index "$project")
-
-	if [[ $# -eq 0 ]]; then
-		print_format "$style_error" "$message_not_enough_args"
-		return 1
-	fi
-
-	if [[ $# -ge 2 ]]; then
-		if is_valid_freeze_command_option "$2"; then
-			local option="$2"
-
-			case "$option" in
-				"$option_branch"|"$option_branch_short")
-					if [[ $# -ne 3 ]]; then
-						print_format "$style_error" "$message_incorrect_num_of_args"
-						return 1
-					else
-						local branch="$3"
-					fi
-					;;
-			esac
-		else
-			print_format "$style_rror" "$message_unknown_arg: $2"
-			printf "$message_usage\n"
-			return 1
-		fi
-	else
-		local branch="$freeze_command_default_branch"
-	fi
-
-	if is_valid_project_for_freeze_command "$project"; then
-		local project_db_name="${project_db_names[$project_i]}"
-		setup_project_branch "$project" 'true' "$branch" 'true' 'true' || return 1
-		create_clean_db "$project_db_name" || return 1
-
-	elif is_valid_project "$project"; then
-		print_format "$style_error" "$message_command_does_not_support_project: '$project'"
-		return 1
-
-	else
-		print_format "$style_error" "$message_unknown_project: '$project'"
-		return 1
-	fi
-
-	return 0
-}
-
-function restore() {
-	local project="$1"
-
-	local -i project_i=$(get_project_index "$project")
-	local delete_db='false'
-
-	if [[ $# -eq 0 ]]; then
-		print_format "$style_error" "$message_not_enough_args"
-		return 1
-	fi
-
-	if [[ $# -ge 2 ]]; then
-		if is_valid_restore_command_option "$2"; then
-			local option="$2"
-
-			case "$option" in
-				"$option_delete"|"$option_delete_short")
-					local delete_db='true'
-					;;
-			esac
-		else
-			print_format "$style_rror" "$message_unknown_arg: $2"
-			printf "$message_usage\n"
-			return 1
-		fi
-	fi
-
-	if is_valid_project_for_freeze_command "$project"; then
-		local project_db_name="${project_db_names[$project_i]}"
-		restore_from_clean_db "$project_db_name" "$delete_db" || return 1
-
-	elif is_valid_project "$project"; then
-		print_format "$style_error" "$message_command_does_not_support_project: '$project'"
-		return 1
-
-	else
-		print_format "$style_error" "$message_unknown_project: '$project'"
-		return 1
-	fi
-
-	return 0
-}
-
-function run() {
-	local project="$1"
-
-	if [[ $# -lt 2 ]]; then
-		print_format "$style_error" "$message_incorrect_num_of_args"
-		return 1
-	fi
-
-	if is_valid_run_command_option "$2"; then
-		local option="$2"
-
-		case "$option" in
-			"$option_branch"|"$option_branch_short")
-				if [[ $# -lt 4 ]]; then
-					print_format "$style_error" "$message_incorrect_num_of_args"
-					return 1
-				else
-					local branch="$3"
-					shift 3
-				fi
-				;;
-		esac
-	else
-		shift
-	fi
-
-	if is_valid_project "$project"; then
-		goto_project "$project" 'false' "$branch" || return 1
-		run_command "$@" || return 1
-	else
-		print_format "$style_error" "$message_unknown_project: '$project'"
-		return 1
-	fi
 
 	return 0
 }
@@ -1362,6 +1201,168 @@ function build() {
 	return 0
 }
 
+function freeze() {
+	local project="$1"
+	local -i project_i=$(get_project_index "$project")
+
+	if [[ $# -eq 0 ]]; then
+		print_format "$style_error" "$message_not_enough_args"
+		return 1
+	fi
+
+	if [[ $# -ge 2 ]]; then
+		if is_valid_freeze_command_option "$2"; then
+			local option="$2"
+
+			case "$option" in
+				"$option_branch"|"$option_branch_short")
+					if [[ $# -ne 3 ]]; then
+						print_format "$style_error" "$message_incorrect_num_of_args"
+						return 1
+					else
+						local branch="$3"
+					fi
+					;;
+			esac
+		else
+			print_format "$style_rror" "$message_unknown_arg: $2"
+			printf "$message_usage\n"
+			return 1
+		fi
+	else
+		local branch="$freeze_command_default_branch"
+	fi
+
+	if is_valid_project_for_freeze_command "$project"; then
+		local project_db_name="${project_db_names[$project_i]}"
+		setup_project_branch "$project" 'true' "$branch" 'true' 'true' || return 1
+		create_clean_db "$project_db_name" || return 1
+
+	elif is_valid_project "$project"; then
+		print_format "$style_error" "$message_command_does_not_support_project: '$project'"
+		return 1
+
+	else
+		print_format "$style_error" "$message_unknown_project: '$project'"
+		return 1
+	fi
+
+	return 0
+}
+
+function restore() {
+	local project="$1"
+
+	local -i project_i=$(get_project_index "$project")
+	local delete_db='false'
+
+	if [[ $# -eq 0 ]]; then
+		print_format "$style_error" "$message_not_enough_args"
+		return 1
+	fi
+
+	if [[ $# -ge 2 ]]; then
+		if is_valid_restore_command_option "$2"; then
+			local option="$2"
+
+			case "$option" in
+				"$option_delete"|"$option_delete_short")
+					local delete_db='true'
+					;;
+			esac
+		else
+			print_format "$style_rror" "$message_unknown_arg: $2"
+			printf "$message_usage\n"
+			return 1
+		fi
+	fi
+
+	if is_valid_project_for_freeze_command "$project"; then
+		local project_db_name="${project_db_names[$project_i]}"
+		restore_from_clean_db "$project_db_name" "$delete_db" || return 1
+
+	elif is_valid_project "$project"; then
+		print_format "$style_error" "$message_command_does_not_support_project: '$project'"
+		return 1
+
+	else
+		print_format "$style_error" "$message_unknown_project: '$project'"
+		return 1
+	fi
+
+	return 0
+}
+
+function run() {
+	local project="$1"
+
+	if [[ $# -lt 2 ]]; then
+		print_format "$style_error" "$message_incorrect_num_of_args"
+		return 1
+	fi
+
+	if is_valid_run_command_option "$2"; then
+		local option="$2"
+
+		case "$option" in
+			"$option_branch"|"$option_branch_short")
+				if [[ $# -lt 4 ]]; then
+					print_format "$style_error" "$message_incorrect_num_of_args"
+					return 1
+				else
+					local branch="$3"
+					shift 3
+				fi
+				;;
+		esac
+	else
+		shift
+	fi
+
+	if is_valid_project "$project"; then
+		goto_project "$project" 'false' "$branch" || return 1
+		run_command "$@" || return 1
+	else
+		print_format "$style_error" "$message_unknown_project: '$project'"
+		return 1
+	fi
+
+	return 0
+}
+
+# TODO: Check that om is in the PATH
+function check() {
+	local set_verbose="$1"
+	local verbose='false'
+	local vars_missing='false'
+
+	if [[ "$verbose_mode" = 'true' || "$set_verbose" = 'true' ]]; then
+		local verbose='true'
+		print_format "$style_command_title" "$message_check"
+	fi
+
+	for ev in "${env_vars_required[@]}"; do
+		if [[ -z "${!ev+x}" ]]; then
+			local vars_missing='true'
+			printf "Checking '$ev'... ${fm_red}UNSET${fm_reset}\n"
+		else
+			if [[ "$verbose" = 'true' ]]; then
+				printf "Checking '$ev'... ${fm_green}OK${fm_reset}\n"
+			fi
+		fi
+	done
+
+	if [[ "$vars_missing" = 'true' ]]; then
+		printf "\n${fm_red}CHECK FAILED${fm_reset}\n"
+		printf "Please set the ${fm_red}UNSET${fm_reset} environment variables above before running the program\n"
+		return 1
+	elif [[ "$verbose" = 'true' ]]; then
+		printf "\n${fm_green}CHECK PASSED${fm_reset}\n"
+	fi
+
+	return 0
+}
+
 function print_config() {
 	jq '.' "$config_filepath"
 }
@@ -1388,28 +1389,31 @@ function handle_command() {
 	local command="$1"
 
 	load_config || return 1
-	check_env || return 1
+	check || return 1
 
 	shift
 
 	case "$command" in
+		"$command_build")
+			build "$@" || return 1
+			;;
 		"$command_freeze")
 			freeze "$@" || return 1
 			;;
 		"$command_restore")
 			restore "$@" || return 1
 			;;
-		"$command_build")
-			build "$@" || return 1
-			;;
 		"$command_run")
 			run "$@" || return 1
 			;;
+		"$command_check")
+			check 'true' || return 1
+			;;
 		"$command_print_config")
-			print_config "$@" || return 1
+			print_config || return 1
 			;;
 		"$command_reset")
-			reset "$@" || return 1
+			reset || return 1
 			;;
 		"$command_scipt_run")
 			script_run "$@" || return 1
